/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.newpackage;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Asife
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Field1 = new javax.swing.JTextField();
        Field2 = new javax.swing.JTextField();
        Field3 = new javax.swing.JTextField();
        Field4 = new javax.swing.JTextField();
        Field5 = new javax.swing.JTextField();
        Field6 = new javax.swing.JTextField();
        Field7 = new javax.swing.JTextField();
        Field8 = new javax.swing.JTextField();
        Field9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("First Game");
        setForeground(new java.awt.Color(102, 255, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tic-Tak-Toe");

        Field1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field1ActionPerformed(evt);
            }
        });

        Field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field2ActionPerformed(evt);
            }
        });

        Field3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field3ActionPerformed(evt);
            }
        });

        Field4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field4ActionPerformed(evt);
            }
        });

        Field6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field6ActionPerformed(evt);
            }
        });

        Field7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Field4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Field8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Field9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Field2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(Field3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Field5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Field6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Field4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Field7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Field9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void Field6ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void Field1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String val1=Field1.getText();
        String val2=Field2.getText();
        String val3=Field3.getText();
        String val4=Field4.getText();
        String val5=Field5.getText();
        String val6=Field6.getText();
        String val7=Field7.getText();
        String val8=Field8.getText();
        String val9=Field9.getText();
        
        // condition
        if(val1.equals("o")&&val2.equals("o")&&val3.equals("o")){
            Field1.setBackground(Color.red);
            Field2.setBackground(Color.red);
            Field3.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"o win...");
            Field1.setBackground(Color.WHITE);
            Field2.setBackground(Color.WHITE);
            Field3.setBackground(Color.WHITE);
        }else if(val1.equals("x")&&val2.equals("x")&&val3.equals("x")){
            Field1.setBackground(Color.red);
            Field2.setBackground(Color.red);
            Field3.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"x win...");
            Field1.setBackground(Color.WHITE);
            Field2.setBackground(Color.WHITE);
            Field3.setBackground(Color.WHITE);
        }
        // case 2 that is 1 4 7
        else if(val1.equals("o")&&val4.equals("o")&&val7.equals("o")){
            Field1.setBackground(Color.red);
            Field4.setBackground(Color.red);
            Field7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"o win...");
            Field1.setBackground(Color.WHITE);
            Field4.setBackground(Color.WHITE);
            Field7.setBackground(Color.WHITE);
        }
        else if(val1.equals("x")&&val4.equals("x")&&val7.equals("x")){
            Field1.setBackground(Color.red);
            Field4.setBackground(Color.red);
            Field7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"x win...");
            Field1.setBackground(Color.WHITE);
            Field4.setBackground(Color.WHITE);
            Field7.setBackground(Color.WHITE);
        }
        // case 3 that is 1 5 9
        else if(val1.equals("o")&&val5.equals("o")&&val9.equals("o")){
            Field1.setBackground(Color.red);
            Field5.setBackground(Color.red);
            Field9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"o win...");
            Field1.setBackground(Color.WHITE);
            Field5.setBackground(Color.WHITE);
            Field9.setBackground(Color.WHITE);
        }
        else if(val1.equals("x")&&val5.equals("x")&&val9.equals("x")){
            Field1.setBackground(Color.red);
            Field5.setBackground(Color.red);
            Field9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"x win...");
            Field1.setBackground(Color.WHITE);
            Field5.setBackground(Color.WHITE);
            Field9.setBackground(Color.WHITE);
        }
    }                                      

    private void Field2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String val1=Field1.getText();
        String val2=Field2.getText();
        String val3=Field3.getText();
        String val4=Field4.getText();
        String val5=Field5.getText();
        String val6=Field6.getText();
        String val7=Field7.getText();
        String val8=Field8.getText();
        String val9=Field9.getText();
        // case 1 in 2 box 2 5 8
        if(val2.equals("o")&&val5.equals("o")&&val8.equals("o")){
            Field2.setBackground(Color.red);
            Field5.setBackground(Color.red);
            Field8.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"o win...");
            Field2.setBackground(Color.WHITE);
            Field5.setBackground(Color.WHITE);
            Field8.setBackground(Color.WHITE);
        }else if(val2.equals("x")&&val5.equals("x")&&val8.equals("x")){
            Field2.setBackground(Color.red);
            Field5.setBackground(Color.red);
            Field8.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"x win...");
            Field2.setBackground(Color.WHITE);
            Field5.setBackground(Color.WHITE);
            Field8.setBackground(Color.WHITE);
        }
    }                                      

    private void Field3ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String val1=Field1.getText();
        String val2=Field2.getText();
        String val3=Field3.getText();
        String val4=Field4.getText();
        String val5=Field5.getText();
        String val6=Field6.getText();
        String val7=Field7.getText();
        String val8=Field8.getText();
        String val9=Field9.getText();
        if(val3.equals("o")&&val5.equals("o")&&val7.equals("o")){
            Field3.setBackground(Color.red);
            Field5.setBackground(Color.red);
            Field7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"o win...");
            Field3.setBackground(Color.WHITE);
            Field5.setBackground(Color.WHITE);
            Field7.setBackground(Color.WHITE);
        }else if(val3.equals("x")&&val5.equals("x")&&val7.equals("x")){
            Field3.setBackground(Color.red);
            Field5.setBackground(Color.red);
            Field7.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"x win...");
            Field3.setBackground(Color.WHITE);
            Field5.setBackground(Color.WHITE);
            Field7.setBackground(Color.WHITE);
        }
        else if(val3.equals("o")&&val6.equals("o")&&val9.equals("o")){
            Field3.setBackground(Color.red);
            Field6.setBackground(Color.red);
            Field9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"o win...");
            Field3.setBackground(Color.WHITE);
            Field6.setBackground(Color.WHITE);
            Field9.setBackground(Color.WHITE);
        }
        else if(val3.equals("x")&&val6.equals("x")&&val9.equals("x")){
            Field3.setBackground(Color.red);
            Field6.setBackground(Color.red);
            Field9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"x win...");
            Field3.setBackground(Color.WHITE);
            Field6.setBackground(Color.WHITE);
            Field9.setBackground(Color.WHITE);
        }
    }                                      

    private void Field4ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String val1=Field1.getText();
        String val2=Field2.getText();
        String val3=Field3.getText();
        String val4=Field4.getText();
        String val5=Field5.getText();
        String val6=Field6.getText();
        String val7=Field7.getText();
        String val8=Field8.getText();
        String val9=Field9.getText();
        if(val4.equals("o")&&val5.equals("o")&&val6.equals("o")){
            Field4.setBackground(Color.red);
            Field5.setBackground(Color.red);
            Field6.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"o win...");
            Field4.setBackground(Color.WHITE);
            Field5.setBackground(Color.WHITE);
            Field6.setBackground(Color.WHITE);
        }else if(val4.equals("x")&&val5.equals("x")&&val6.equals("x")){
            Field4.setBackground(Color.red);
            Field5.setBackground(Color.red);
            Field6.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"x win...");
            Field4.setBackground(Color.WHITE);
            Field5.setBackground(Color.WHITE);
            Field6.setBackground(Color.WHITE);
        }
    }                                      

    private void Field7ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String val1=Field1.getText();
        String val2=Field2.getText();
        String val3=Field3.getText();
        String val4=Field4.getText();
        String val5=Field5.getText();
        String val6=Field6.getText();
        String val7=Field7.getText();
        String val8=Field8.getText();
        String val9=Field9.getText();
        if(val7.equals("o")&&val8.equals("o")&&val9.equals("o")){
            Field7.setBackground(Color.red);
            Field8.setBackground(Color.red);
            Field9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"o win...");
            Field7.setBackground(Color.WHITE);
            Field8.setBackground(Color.WHITE);
            Field9.setBackground(Color.WHITE);
        }else if(val7.equals("x")&&val8.equals("x")&&val9.equals("x")){
            Field7.setBackground(Color.red);
            Field8.setBackground(Color.red);
            Field9.setBackground(Color.red);
            JOptionPane.showMessageDialog(this,"x win...");
            Field7.setBackground(Color.WHITE);
            Field8.setBackground(Color.WHITE);
            Field9.setBackground(Color.WHITE);
        }
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Field1;
    private javax.swing.JTextField Field2;
    private javax.swing.JTextField Field3;
    private javax.swing.JTextField Field4;
    private javax.swing.JTextField Field5;
    private javax.swing.JTextField Field6;
    private javax.swing.JTextField Field7;
    private javax.swing.JTextField Field8;
    private javax.swing.JTextField Field9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
